name: Composer DAGs CI/CD for Production 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Configure env variables
env:
  DAGS_BUCKET_PATH: gs://learning-composer-prd/dags/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Defines the workflow job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps will be executed as part of the job
    steps:
      # Clone the repository
      - uses: actions/checkout@v3

      # Performs authentication on Google Cloud with a json credential allocated in secret github
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configura o Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      # Runs command gsutil for syns dags
      - name: Upload dags to Cloud Storage
        run: |
          gsutil -m rsync -r dags/*.py ${{ env.DAGS_BUCKET_PATH }}
