name: Composer dags CI/CD for develop

on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Configure env variables
env:
  DAGS_BUCKET_PATH: gs://learning-composer-dsv/dags/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Defines the workflow job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps will be executed as part of the job
    steps:
      # Clone the repository
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      # Runs tests unit in dags    
      - name: Run tests
        run: |
          python -m pytest -s tests/

      # Performs authentication on Google Cloud with a json credential allocated in secret github
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configura o Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      # Runs command gsutil for syns dags
      - name: Upload dags to Cloud Storage
        run: |
          gsutil -m rsync -r -x "__pycache__" dags ${{ env.DAGS_BUCKET_PATH }}
